---
# Service
apiVersion: v1
kind: Service
metadata:
  name: manual-aws-women-hello-api-sv
spec:
  selector:
    app.kubernetes.io/name: manual-aws-women-hello-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
# Source: Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manual-aws-women-hello-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: manual-aws-women-hello-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: manual-aws-women-hello-api
    spec:
      securityContext:
        {}
      containers:
        - name: java-app
          securityContext:
            {}
          image: "984724474376.dkr.ecr.us-east-2.amazonaws.com/manual-aws-women-hello-api:1.0.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/actuator/health
              port: http
          readinessProbe:
            httpGet:
              path: /api/actuator/health
              port: http
          resources:
            {}
